package com.wonders.health.tumor.tumor.webservice;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.2
 * 2019-06-27T10:54:43.539+08:00
 * Generated source version: 3.3.2
 *
 */
@WebService(targetNamespace = "http://www.winning.com.cn/KWS/", name = "KWSServiceSoap")
//@XmlSeeAlso({ObjectFactory.class})
public interface KWSServiceSoap {

    @WebMethod(operationName = "HelloWorld", action = "http://www.winning.com.cn/KWS/HelloWorld")
    @RequestWrapper(localName = "HelloWorld", targetNamespace = "http://www.winning.com.cn/KWS/", className = "cn.com.winning.kws.HelloWorld")
    @ResponseWrapper(localName = "HelloWorldResponse", targetNamespace = "http://www.winning.com.cn/KWS/", className = "cn.com.winning.kws.HelloWorldResponse")
    @WebResult(name = "HelloWorldResult", targetNamespace = "http://www.winning.com.cn/KWS/")
    public java.lang.String helloWorld(

        @WebParam(name = "InXml", targetNamespace = "http://www.winning.com.cn/KWS/")
        java.lang.String inXml
    );

    @WebMethod(operationName = "DbSetting", action = "http://www.winning.com.cn/KWS/DbSetting")
    @RequestWrapper(localName = "DbSetting", targetNamespace = "http://www.winning.com.cn/KWS/", className = "cn.com.winning.kws.DbSetting")
    @ResponseWrapper(localName = "DbSettingResponse", targetNamespace = "http://www.winning.com.cn/KWS/", className = "cn.com.winning.kws.DbSettingResponse")
    public void dbSetting(

        @WebParam(name = "key", targetNamespace = "http://www.winning.com.cn/KWS/")
        java.lang.String key,
        @WebParam(mode = WebParam.Mode.INOUT, name = "settinginfo", targetNamespace = "http://www.winning.com.cn/KWS/")
        javax.xml.ws.Holder<java.lang.String> settinginfo,
        @WebParam(mode = WebParam.Mode.OUT, name = "DbSettingResult", targetNamespace = "http://www.winning.com.cn/KWS/")
        javax.xml.ws.Holder<java.lang.Boolean> dbSettingResult
    );

    @WebMethod(operationName = "WebBusiness", action = "http://www.winning.com.cn/KWS/WebBusiness")
    @RequestWrapper(localName = "WebBusiness", targetNamespace = "http://www.winning.com.cn/KWS/", className = "cn.com.winning.kws.WebBusiness")
    @ResponseWrapper(localName = "WebBusinessResponse", targetNamespace = "http://www.winning.com.cn/KWS/", className = "cn.com.winning.kws.WebBusinessResponse")
    @WebResult(name = "WebBusinessResult", targetNamespace = "http://www.winning.com.cn/KWS/")
    public java.lang.String webBusiness(

        @WebParam(name = "TranCode", targetNamespace = "http://www.winning.com.cn/KWS/")
        java.lang.String tranCode,
        @WebParam(name = "InXml", targetNamespace = "http://www.winning.com.cn/KWS/")
        java.lang.String inXml
    );
}
