package com.wonders.health.tumor.tumor.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.2
 * 2019-07-09T16:38:53.514+08:00
 * Generated source version: 3.3.2
 *
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "TechBookServiceSoap")
//@XmlSeeAlso({ObjectFactory.class})
public interface TechBookServiceSoap {

    /**
     * 确认预约
     */
    @WebMethod(operationName = "ExecBook", action = "http://tempuri.org/ExecBook")
    @RequestWrapper(localName = "ExecBook", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ExecBook")
    @ResponseWrapper(localName = "ExecBookResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ExecBookResponse")
    @WebResult(name = "ExecBookResult", targetNamespace = "http://tempuri.org/")
    public String execBook(

            @WebParam(name = "input", targetNamespace = "http://tempuri.org/")
            String input
    );

    /**
     * 取消预约
     */
    @WebMethod(operationName = "CancelBook", action = "http://tempuri.org/CancelBook")
    @RequestWrapper(localName = "CancelBook", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CancelBook")
    @ResponseWrapper(localName = "CancelBookResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CancelBookResponse")
    @WebResult(name = "CancelBookResult", targetNamespace = "http://tempuri.org/")
    public String cancelBook(

            @WebParam(name = "input", targetNamespace = "http://tempuri.org/")
            String input
    );

    /**
     * 项目排班信息查询
     */
    @WebMethod(operationName = "QueryScheduleDetailInfo", action = "http://tempuri.org/QueryScheduleDetailInfo")
    @RequestWrapper(localName = "QueryScheduleDetailInfo", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QueryScheduleDetailInfo")
    @ResponseWrapper(localName = "QueryScheduleDetailInfoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QueryScheduleDetailInfoResponse")
    @WebResult(name = "QueryScheduleDetailInfoResult", targetNamespace = "http://tempuri.org/")
    public String queryScheduleDetailInfo(

            @WebParam(name = "input", targetNamespace = "http://tempuri.org/")
            String input
    );
}
